### ISSUE TITLE
Brightness set to 100% when you adjust the color temperature

### ISSUE THREAD

**Issue by basesnow** [JoshuaMulliken/ha-wyzeapi#13]
Hi, still seeing the problem on v0.3.1. I installed and updated through HACS, then restarted the server (not sure if that matters compared to a reboot). Ran the logger and didn't get any warnings for Wyzeapi.

I am adjusting the lights in Lovelace using both the standard entity card and the [light entry row](https://github.com/custom-cards/light-entity-row) plugin.

It also has the same issue when I use the card pop up (card that shows up when you click on the picture of the lightbulb) and adjust the lights.

**Comment by JoshuaMulliken** [comment]
Can you add

``` yaml
logger:
  default: warning
  logs:
    custom_components.wyzeapi: debug
```

To your `configuration.yaml` restart and then send me your `home-assistant.log` file from your `/config` folder?

**Comment by basesnow** [comment]
Will do. Might take some time though. Home assistant completely crashed and I can’t do a clean install right now. I think it has something to do with the 103.1 release of hass.io. Read that version is preventing the front end from displaying. Hopefully 103.2 will be available for me soon.

**Comment by JoshuaMulliken** [comment]
Ok sounds good. When you rebuild, make sure you are using:
```yaml
light:
  - platform: wyzeapi
     username: <email for wyze>
     password: <password for wyze>
```
In your `configuration.yaml`
