### ISSUE TITLE
Invalid config when following example in README

### ISSUE THREAD

**Issue by kprestel** [JoshuaMulliken/ha-wyzeapi#17]
When following the example in the `README` I get an error for both the switch and the lights.

Error log:

> Invalid config for [light]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 97). Please check the docs at https://home-assistant.io/integrations/light/

> Invalid config for [light.wyzeapi]: required key not provided @ data['password']. Got None
required key not provided @ data['username']. Got None. (See /config/configuration.yaml, line 96). Please check the docs at https://home-assistant.io/integrations/wyzeapi/

Same thing for lights:

> Invalid config for [switch]: required key not provided @ data['platform']. Got None. (See /config/configuration.yaml, line 102). Please check the docs at https://home-assistant.io/integrations/switch/

> Invalid config for [switch.wyzeapi]: required key not provided @ data['password']. Got None
required key not provided @ data['username']. Got None. (See /config/configuration.yaml, line 101). Please check the docs at https://home-assistant.io/integrations/wyzeapi

Relevant snippet from `configuration.yaml`:

```yaml
light:
  - platform: wyzeapi    
  - username: !secret wyze_username
  - password: !secret wyze_password

switch:
  - platform: wyzeapi    
  - username: !secret wyze_username
  - password: !secret wyze_password
```
I tried hard coding the username and password the same behavior exists.

I have HASS running in docker on a raspberry pi 4, and installed this through HACS. 

Let me know if you need anything else from me.

Thanks!

**Comment by JoshuaMulliken** [comment]
Hello you are not using the correct syntax please use this 
```Yaml
light:
  - platform: wyzeapi
     username: <email for wyze>
     password: <password for wyze>

switch:
  - platform: wyzeapi
     username: <email for wyze>
     password: <password for wyze>

```
