### ISSUE TITLE
[Bug] Scene.create not working with Wyze bulbs

### ISSUE THREAD

**Issue by drguitarum2005** [JoshuaMulliken/ha-wyzeapi#257]
Is there any reason to believe this integration would make the light entities act any different than other bulbs? I'm using a scene.create in a script to snapshot initial state before changing colors and brightness and then reverting to that initial scene. The scene.create doesn't seem to be writing anything. This exact code works fine with my Singled color bulbs. Thoughts?

```
sequence:
  - service: scene.create
    data:
      scene_id: entry_before
      snapshot_entities: light.entry_lamp
  - service: light.turn_on
    data:
      color_name: red
      flash: long
      brightness_pct: 25
    target:
      entity_id: light.entry_lamp
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: light.turn_on
    data:
      color_name: red
      brightness_pct: 25
      flash: long
    target:
      entity_id: light.entry_lamp
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: scene.turn_on
    target:
      entity_id: scene.entry_before
mode: single
alias: Flash Entry Light Red
```
