### ISSUE TITLE
[BUG] Dimming level missing from emulated_hue exposed lights in Alexa

### ISSUE THREAD

**Issue by jamman9000** [JoshuaMulliken/ha-wyzeapi#30]
**Describe the bug**
In HA, it’s possible to see and set dimming level in Lovelace but when exposing the light via emulated hue to Alexa the dimming ability is missing. The selection is no longer in the Alexa device page (new devices after installing this integration) whereas it was there when I exposed custom light entities that used IFTTT to talk to Wyze Bulbs.

**To Reproduce**
1. Install via HACS
2. Restart and populate HA with the new light entities
3. Configure emulated_hue component to expose the light entities to Alexa
4. Discover lights in Alexa
5. Open the device settings page and only see the on/off button and temperature settings available.

**Expected behavior**
Dimming available in Alexa

**System configuration**
System: Hass.io in Proxmox VM
HA Version: v0.104.0
WyzeApi Version: v0.4.1

**configuration.yaml**
```yaml
wyzeapi:
  wyze_username: !secret wyze_un
  wyze_password: !secret wyze_pw
```
```
emulated_hue:
  host_ip: 10.0.0.170
  listen_port: 80
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: false
  entities:
    switch.game_room_plug_relay:
      name: "Game Room Plug"
      hidden: false
    switch.work_pc_plug_relay:
      name: "Work PC Plug New"
      hidden: false
    switch.nadia_mirror_relay:
      name: "Nadia's Mirror"
      hidden: false
    #light.dining_room:
      #name: "Dining Room"
      #hidden: false
    light.mud_room_light:
      name: "Mudroom Light"
      hidden: false
    switch.cpap_plug_relay:
      name: "CPAP Plug"
      hidden: false
    switch.mbr_tv_plug_relay:
      name: "Master Bedroom TV Plug"
      hidden: false
    light.jason_s_bed_light:
      name: "Jason's Bed Light"
      hidden: false
    light.living_room_bulb_1:
      name: "Living Room Bulb 1"
      hidden: false
    light.living_room_bulb_2:
      name: "Living Room Bulb 2"
      hidden: false
    light.nadia_s_bed_light:
      name: "Nadia's Bed Light"
      hidden: false
    light.penny_s_light:
      name: "Penny's Light"
      hidden: false
    light.kitchen_light:
      name: "Kitchen Light"
      hidden: false
    light.office_light:
      name: "Office Light"
      hidden: false
```

**home-assistant.log**
```
No logs of note related to this component
```
