### ISSUE TITLE
[Bug] Wyze color bulb transition not working

### ISSUE THREAD

**Issue by 3Necromancer** [JoshuaMulliken/ha-wyzeapi#329]
I have a wyze color bulb connected, I use call service -> light turn off with the bulb entity and transition 60, but it turns off immediately. 
same with turn on.

It works well with my LIFX bulbs. 

![image](https://user-images.githubusercontent.com/4170102/151023562-ecc2d1b5-08f7-4712-a46e-1149ed58d6f6.png)

**Comment by yoinx** [comment]
I don't have any bulbs, but afaik wyze bulbs don't support transitions.

**Comment by brg468** [comment]
I can confirm, they do not support transition.

**Comment by 3Necromancer** [comment]
can it be emulated ? sending a few pulses to change the brightness over a period of time?
pulse = brightness_difference/transition_time*3 
gives the change in brightness for 3 seconds, 
brightness_difference/pulse gives the amount of pulses needed to achieve the change in brightness over the defined period of time.

**Comment by tggman** [comment]
> can it be emulated ? sending a few pulses to change the brightness over a period of time? pulse = brightness_difference/transition_time*3 gives the change in brightness for 3 seconds, brightness_difference/pulse gives the amount of pulses needed to achieve the change in brightness over the defined period of time.

I've written code that emulates light brightness transitions, but it fails to work reliably due to Wyze Rate limiting. Here's the code if you want to try it yourself. I've tested/confirmed this code using LIFX bulbs:
```
# ----------------------------------------------------------- #
# Purpose: Transition light brightness over a period of time
#
# Service Call:
# service: script.light_transition
# data:
#   light_entities: light.lifx_color_800tkg02                        #-: [ ... ]
#   brightness: 255                                                  #-: (1-255) or brightness_pct (0-100)
#   color_temp: 235
#   transition: 360                                                  #-: time in seconds
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
light_transition:
  alias: "Light Brightness Transition"
  variables:
    fade_time_sec:  "{{ transition }}"                                         #-: time to transition brightness (actual may be slightly longer)
    fade_time_msec: "{{ fade_time_sec | float(0) * 1000 }}"
    brightness: "{{ [brightness_pct|default(-1) * 255/100, brightness|default(-1)] | max|round(0,'round-to-even',0) }}" #-: convert % to byte as reqiured
    delay_time_msec: "{{ fade_time_msec / brightness }}"                       #-: max brightness: 255/fade_time_sec  = msec / Index (0-255)
  # delay_time_msec: "{{ fade_time_msec / 100 }}"                              #-: brightness_pct: 100%/fade_time_sec = msec / 1.0% (0-100%)
    fade_loop_count: "{{ (fade_time_msec / delay_time_msec)|round(0,'round-to-even',0) }}"     #-: should work out to 255 (or 100%)
  mode: parallel
  sequence:
    - service: light.turn_on
      data:
        entity_id: "{{ entity_id }}"
        brightness: 1
        color_temp: "{{ color_temp }}"
    - wait_template: "{{ is_state(entity_id, 'on') }}"
      timeout: 5                                                               #-: timeout value should be an eternity
      continue_on_timeout: false                                               #-: abort the script if timeout duration expires
    - repeat:                                                                  # START repeat
        sequence:
          - wait_template: "{{ is_state(entity_id, 'off') }}"                  # delay + check to see if light was turned off manually 
            timeout:
              milliseconds: "{{ delay_time_msec }}"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
          - choose:                                                                 # if (light was NOT turned off) then
              conditions: "{{ not wait.completed }}"                                # ..
              sequence:                                                             # .. continue the brightness transition process
                service: light.turn_on                                              # ..
                data:                                                               # ..
                  entity_id: "{{ entity_id }}"                                      # ..
                  brightness: "{{ (brightness/fade_loop_count * repeat.index)|int(0) }}"  # 255  / TotalLoopCount * CurrentLoopCount
                # brightness_pct: "{{ (100/fade_loop_count * repeat.index)|int(0) }}"     # 100% / TotalLoopCount * CurrentLoopCount
            #default:                                                               # else (do nothing)
            #[end.choose]#                                                          # endif
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
        until: "{{ is_state(entity_id, 'off') or (repeat.index > fade_loop_count) }}"
#   - END repeat                                                               # END repeat
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
```
